/*! Gstat marker v10.3.0 */
var GSTAT_VERSION="10.3.0",_gsrc_smo=[];function smo(a,b){this.code=a;this.regex=b}_gsrc_smo[0]=new smo("FBO","^.*\\.facebook\\.com");_gsrc_smo[1]=new smo("TWI","^(t\\.co|twitter\\.com)");_gsrc_smo[2]=new smo("GPL","^(plus.*)\\.google\\.com");_gsrc_smo[3]=new smo("DAI","^.*\\.dailymotion\\.com");_gsrc_smo[4]=new smo("PIN","^.*pinterest\\.com");_gsrc_smo[5]=new smo("LIN","^.*\\.linkedin\\.com");_gsrc_smo[6]=new smo("FLK","^.*\\.flickr\\.(com|fr)");_gsrc_smo[7]=new smo("VIA","^.*\\.viadeo\\.com");
_gsrc_smo[8]=new smo("MYS","^.*\\.myspace\\.com");_gsrc_smo[9]=new smo("YOU","^.*\\.youtube\\.com");_gsrc_smo[10]=new smo("TUM","^.*\\.tumblr\\.com");_gsrc_smo[11]=new smo("FOU","^.*\\.foursquare\\.com");var _gsrc_seo=[];function seo(a,b,e,d){this.code=a;this.regex=b;this.param=e;this.paramLien=d}_gsrc_seo[0]=new seo("LMT","(.*\\.ke\\.voila.fr)|(www\\.lemoteur\\.fr)|(lemoteur\\.fr)|(lemoteur\\.orange\\.fr)|(presse\\.lemoteur\\.fr)|(moteur\\.voila\\.fr/S/(orange|wanadoo|voila))","rdata=|kw=|qw=","");
_gsrc_seo[1]=new seo("ASS","^assistance\\.orange\\.fr/recherche\\.php","kw=","");_gsrc_seo[2]=new seo("GOO","^(images\\.|news\\.|blogsearch\\.|directory\\.|www\\.|ww\\.|w\\.)?google\\.","q=|search=","goo");_gsrc_seo[3]=new seo("BIN","^www\\.bing\\.com","q=","bin");_gsrc_seo[4]=new seo("YAH","(search|search\\.tw|search\\.espanol)\\.yahoo\\.com","p=","yah");_gsrc_seo[5]=new seo("ASK","^(fr|es|de|it|nl|uk|web)\\.ask\\.com","q=|ask=","");
_gsrc_seo[6]=new seo("AOL","^(aolbusqueda|aolsearch|aolsearcht|recherche|search|suche|www\\.recherche)\\.aol\\.(ca|com|fr|de|co\\.uk|com\\.mx)","q=|query=","aol");_gsrc_seo[7]=new seo("ALT","^((...|..)\\.altavista\\.com)","q=","");_gsrc_seo[8]=new seo("MWS","^(kf\\.mysearch|ki\\.mysearch|ms114|ms146|search|mysearch|searchfr|www)\\.(myway|mysearch|mywebsearch)\\.com","searchfor=","");_gsrc_seo[9]=new seo("EXA","^(partner|www)\\.exalead\\.(com|fr|es)","q=","");
_gsrc_seo[10]=new seo("BAI","^(www|www1)\\.baidu\\.com","wd=|word=","");for(var END_OF_INPUT=-1,base64Chars="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".split(""),reverseBase64Chars=[],i=0;i<base64Chars.length;i++)reverseBase64Chars[base64Chars[i]]=i;var base64Str,base64Count;function setBase64Str(a){base64Str=a;base64Count=0}
function readBase64(){if(!base64Str||base64Count>=base64Str.length)return END_OF_INPUT;var a=base64Str.charCodeAt(base64Count)&255;base64Count++;return a}
function encodeBase64(a){setBase64Str(a);a="";for(var b=[3],e=0,d=!1;!d&&(b[0]=readBase64())!=END_OF_INPUT;)b[1]=readBase64(),b[2]=readBase64(),a+=base64Chars[b[0]>>2],b[1]!=END_OF_INPUT?(a+=base64Chars[b[0]<<4&48|b[1]>>4],b[2]!=END_OF_INPUT?(a+=base64Chars[b[1]<<2&60|b[2]>>6],a+=base64Chars[b[2]&63]):(a+=base64Chars[b[1]<<2&60],a+="=",d=!0)):(a+=base64Chars[b[0]<<4&48],a+="=",a+="=",d=!0),e+=4,76<=e&&(a+="\n",e=0);return a}
var _gstat={GSTAT_VERSION:"gstatv="+GSTAT_VERSION,GIF_ORIGINAL_WEB2:"w2.gstat.orange.fr/_gstat.gif",GIF_GSTAT_WEB1:"s.gstat.orange.fr/w1/_gstat.gif",GIF_GSTAT_WEB2:"s.gstat.orange.fr/w2/_gstat.gif",GIF_GSTAT_VIDEO:"s.gstat.orange.fr/video/_gstat.gif",SRC_CAMPAIGN_PARAM:"gst_idc",SRC_TYPE_ACC:"ACC",SRC_TYPE_SMO:"SMO",SRC_TYPE_SEO:"SEO",SRC_TYPE_SEM:"SEM",SRC_TYPE_NDE:"NDE",SRC_TYPE_NTY:"NTY",Cookie:{set:function(a,b,e,d,c,g){var h="";void 0!=e&&(h=new Date,h.setTime(h.getTime()+864E5*parseFloat(e)),
h="; expires="+h.toGMTString());document.cookie=a+"="+escape(b||"")+h+(d?"; path="+d:"")+(c?"; domain="+c:"")+(g?"; secure":"")},get:function(a){var b=document.cookie,e=b.indexOf(a+"=");if(!e&&a!=b.substring(0,a.length)||-1>=e)return null;a=e+a.length+1;e=b.indexOf(";",a);-1==e&&(e=b.length);return unescape(b.substring(a,e))},remove:function(a,b,e,d){var c=_gstat.Cookie.get(a);c&&_gstat.Cookie.set(a,"",-730,b,e,d);return c},test:function(){var a,b=_gstat.createUID();"boolean"==typeof navigator.cookieEnabled?
a=navigator.cookieEnabled:(_gstat.Cookie.set("_gstatCookieSupportTest",b),a=_gstat.Cookie.remove("_gstatCookieSupportTest"));a?(_gstat.Cookie.set("_gstatCookieSupportTest",b),a=_gstat.Cookie.get("_gstatCookieSupportTest")==b?-1:1,_gstat.Cookie.remove("_gstatCookieSupportTest")):a=0;return a}},getCookieDomain:function(){var a=document.domain;if(/^([0-9]{1,3}\.){3}[0-9]{1,3}$/.test(a))return a;if(-1!=a.indexOf("."))return a=a.split("."),2<a.length&&(a=a.slice(a.length-2)),"."+a.join(".")},createUID:function(){return Math.floor(2147483647*
Math.random()+1)+"."+(new Date).getTime()},checkUID:function(a){return RegExp("^[0-9]{3,11}\\.[0-9]{11,14}$","g").test(a)},getUID:function(){var a,b=0;a=_gstat.Cookie.test();-1==a?((a=_gstat.Cookie.get("_gstat"))&&""!=a?!1==_gstat.checkUID(a)&&(b=2):b=1,0<b&&(a=_gstat.createUID()),_gstat.Cookie.set("_gstat",a,730,"/",_gstat.getCookieDomain())):b=3;return a+"&ckregen="+b},getProtocol:function(){var a="http";"https"==document.URL.substr(0,5).toLowerCase()&&(a="https");return a},getReferrer:function(a){var b=
"";return b=a&&""!=a?escape(a):""!=document.referrer?escape(document.referrer):"0"},getSrcDetection:function(a,b){var e="",d="",c="",g=e="",h="",f="",k=!1;if((f=void 0!=a&&a?a:document.referrer)&&""!=f){if(0>f.indexOf("://"))return"";""==b||void 0==b?(e=document.location.search,""===e&&(e=document.location.hash,e=e.substr(e.indexOf("?")+1))):e=b.substr(b.indexOf("?")+1);if(""!=e&&-1<e.indexOf(_gstat.SRC_CAMPAIGN_PARAM+"="))d=e.indexOf(_gstat.SRC_CAMPAIGN_PARAM+"=")+_gstat.SRC_CAMPAIGN_PARAM.length+
1,d=e.substr(d),c=-1<d.indexOf("&")?d.substr(0,d.indexOf("&")):d,d=_gstat.SRC_TYPE_NTY,k=!0;else if(-1<f.indexOf("://")&&(f=f.substr(f.indexOf("://")+3,f.length)),g=-1<f.indexOf("?")?f.substring(0,f.indexOf("?")):-1<f.indexOf("#")?f.substring(0,f.indexOf("#")):f,-1<f.indexOf("?")?h=f.substring(f.indexOf("?")+1,f.length):-1<f.indexOf("#")&&(h=f.substring(f.indexOf("#")+1,f.length)),""!=g){for(f=0;f<_gsrc_smo.length;f++)""!=_gsrc_smo[f].regex&&null!=g.match(_gsrc_smo[f].regex)&&(d=_gstat.SRC_TYPE_SMO,
c=_gsrc_smo[f].code,k=!0);if(!1==k)for(f=0;f<_gsrc_seo.length;f++)if(""!=_gsrc_seo[f].regex&&null!=g.match(_gsrc_seo[f].regex))for(var m=_gsrc_seo[f].param.split("|"),l=0,n=!1;l<m.length&&!1==n;)-1<h.indexOf(m[l])&&(d=-1<e.indexOf("gstso=")&&-1<e.indexOf("gstkw=")&&-1<e.indexOf("esvcid=")?_gstat.SRC_TYPE_SEM:_gstat.SRC_TYPE_SEO,c=_gsrc_seo[f].code,k=n=!0),l++}}else d=_gstat.SRC_TYPE_ACC,c="0",k=!0;!1==k&&(d=_gstat.SRC_TYPE_NDE,c="0");e="&srct="+escape(encodeBase64(d));return e=d==_gstat.SRC_TYPE_NTY?
e+("&srcid="+c):e+("&srcid="+escape(encodeBase64(c)))},amount:!1,setAmount:function(a){isNaN(parseFloat(a.toString()))||"undefined"==typeof a?this.amount=!1:this.amount=a},dummy:function(){return!0},pause:function(a){var b=new Date;for(a=b.getTime()+a;b.getTime()<a;)b=new Date},setImg:function(a,b){var e=new Image(1,1);e.onLoad=function(){_gstat.dummy()};e.src=a;"undefined"!=typeof b&&b&&0<b&&_gstat.pause(b)},web2:function(a,b,e,d,c,g){_gstat.web2_psup(a,b,e,d,c,g,"")},web2_psup:function(a,b,e,d,
c,g,h){var f=a.split(":");a="https"==f[0]||"http"==f[0]?a+"?":_gstat.getProtocol()+"://"+a+"?";a+="uid="+_gstat.getUID();a+="&ty="+(_gstat.Cookie.get("ty")||"0");a+="&svc="+escape(b||"");a+="&ptf="+escape(e||"");a+="&act="+escape(d||"");a+="&ept="+escape(c||"");a+="&"+_gstat.GSTAT_VERSION;a+="&rnd="+Math.floor(1E10*Math.random()+1);h&&(a+="&"+h);_gstat.setImg(a,g)},web1:function(a,b,e,d,c){_gstat.web1_uid(a,"",b,e,d,c)},web1_uid:function(a,b,e,d,c,g){var h=0;a=_gstat.getProtocol()+"://"+a+"?";b?(a+=
"uid="+b,h+=4):a+="uid="+_gstat.getUID();c?(a+="&sn="+escape(c),h+=1):a=""!=window.location.hostname?a+("&sn="+escape(window.location.hostname)):a+"&sn=localhost";b="";c=_gstat.get_magic_id_list();null!=c&&""!=c&&(b+="&mig_l="+escape(c));var f=c="",k=_gstat.getCookie("ap_ofr");"undefined"==typeof k?c=f="":(k=k.split(":"),"undefined"!=typeof k[0]&&(f=escape(k[0])),"undefined"!=typeof k[1]&&(c=escape(k[1])));b+="&gst_idp="+f+"&gst_pc="+c;1==_gstat.getCookie("optout")&&(b+="&optout=1");c=_gstat.gst_clean_pn(window.location.href.substring(window.location.protocol.length+
2+window.location.hostname.length));g?(typeof c[1]&&""!=c[1]||(c=_gstat.gst_clean_pn(g)),a+="&pn="+escape(g),h+=2):a+="&pn="+escape(c[0]);a=a+b+c[1];e&&(a+="&"+e);a+="&ty="+(_gstat.Cookie.get("ty")||"0");a+="&rfr="+_gstat.getReferrer(d);a+=_gstat.getSrcDetection(d);!1!=_gstat.amount&&(a+="&g_ca="+_gstat.amount);a+="&"+_gstat.getResolution();a+="&"+_gstat.GSTAT_VERSION;a+="&rnd="+Math.floor(1E10*Math.random()+1);0<h&&(a+="&forced="+h,4<=h&&(a+="&real_uid="+_gstat.getUID()));a+="&time_netlat=0";a+=
"&time_pgload=0";_gstat.setImg(a,0)},get_magic_id_list:function(){var a="",b=document.body.innerHTML.match(RegExp("(\x3c!-- mig:.*--\x3e)","g"));if(null!=b)for(var e=0;e<b.length;e++)for(var d=b[e].split("\x3c!-- "),c=1;c<d.length;c++)if(null!=d[c]&&""!=d[c]&&"m"==d[c].charAt(0)&&"i"==d[c].charAt(1)&&"g"==d[c].charAt(2)&&":"==d[c].charAt(3)){var g=d[c].split(":")[1].split(" "),a=a+g[0];""!=a&&","!=a.charAt(a.length-1)&&(e<b.length-1?a+=",":c<d.length-1&&(a+=","))}return a},gst_clean_pn:function(a){var b=
null,b=a.split("?");if(1<b.length){a=b[1].split("&");for(var e="",d="",c=0;c<a.length;c++)if("g"==a[c].charAt(0)&&"s"==a[c].charAt(1)&&"t"==a[c].charAt(2)&&"_"==a[c].charAt(3))e+="&"+a[c];else if("g"==a[c].charAt(0)&&"s"==a[c].charAt(1)&&"t"==a[c].charAt(2)&&"s"==a[c].charAt(3)&&"o"==a[c].charAt(4)&&"="==a[c].charAt(5)){var g="",g=a[c].split("=");"google"==g[1]?(g="gstso=GOO&gstsorec="+g[1],d=""==d?d+("?"+g):d+("&"+g)):"yahoo"==g[1]?(g="gstso=YAH&gstsorec="+g[1],d=""==d?d+("?"+g):d+("&"+g)):d=""==
d?d+("?"+a[c]):d+("&"+a[c])}else d=""==d?d+("?"+a[c]):d+("&"+a[c]);b=[b[0]+d,e]}else b=[a,""];return b},getCookie:function(a){var b,e,d,c=document.cookie.split(";"),g=RegExp("^\\s+|\\s+$","g");for(b=0;b<c.length;b++)if(e=c[b].substr(0,c[b].indexOf("=")),d=c[b].substr(c[b].indexOf("=")+1),e=e.replace(g,""),e==a)return unescape(d)},audience_moteur_orange:function(a,b,e,d){_gstat.web1_uid(_gstat.GIF_GSTAT_WEB1,a,b,"",e,d)},audience:function(a,b,e){_gstat.web1(_gstat.GIF_GSTAT_WEB1,a,"",b,e)},audience_custom:function(a,
b,e,d){_gstat.web1(d,a,"",b,e)},log:function(a,b,e,d,c){_gstat.web2(_gstat.GIF_GSTAT_WEB2,a,b,e,d,c)},web2_original:function(a,b,e,d,c){_gstat.web2(_gstat.GIF_ORIGINAL_WEB2,a,b,e,d,c)},log_clic_magic:function(a,b,e,d,c,g,h,f,k,m,l){if("Prod"==a||"Rec"==a||"Dev"==a){e||(e="no_page");"/"==e.charAt([e.length-1])&&(e=e.substr(0,e.length-1));l||(l=250);var n="clic";f&&(10<f&&(f=10),n=n+","+f);n=n+":"+k+"~"+m;c=c.substr(0,3)+"00";h=h.split(RegExp(",","g"));f="";for(k=0;2>k;k++)0<k&&2>k&&(f+=","),k<h.length&&
(f+=h[k]);_gstat.web2_psup(_gstat.GIF_GSTAT_WEB2,"Animation",a,n,e+","+d+","+c+","+g+","+f,l,"magic_id="+b)}},log_video:function(a,b,e,d,c,g,h){var f=window.location,k=escape(f.hostname),f=escape(f.href.substring(f.protocol.length+2+f.hostname.length));_gstat.web2_psup(_gstat.GIF_GSTAT_VIDEO,"Video","Prod",a,c+"~"+h+","+(b+"~"+e+"~"+d+"~"+g),250,"sn="+k+"&pn="+f)},processLinkOnClick:function(a,b){if(a&&a.href&&a.tagName&&"a"===a.tagName.toLowerCase()){var e="http://r.orange.fr/r",d={gst_idm:b||null,
gst_ty:_gstat.Cookie.get("ty"),gst_pc:"",gst_idp:"",rnd:Math.floor(1E10*Math.random()+1),url:a.href},c=_gstat.getCookie("ap_ofr");c&&(c=c.split(":"),"undefined"!==typeof c[0]&&(d.gst_idp=c[0]),"undefined"!==typeof c[1]&&(d.gst_pc=c[1]));if(/^https?:\/\/r.orange.fr\/[rl]/i.test(d.url)){c=d.url.split("?");e=c[0];if("undefined"!==typeof c[1])for(var g=c[1].split("&"),h=0,f=g.length;h<f;h++){var k=g[h].split("=");if("undefined"!==typeof k[0]&&"undefined"!==k[1]){var m=k[0],k=unescape(k[1]);"undefined"===
typeof d[m]?d[m]=k:"url"===m&&(d.url=k)}}"undefined"!==typeof c[1]&&-1!==c[1].indexOf("url=")||delete d.url}var c=[],l;for(l in d)"url"!==l&&c.push(l+"="+escape(null!==d[l]?d[l]:0));"undefined"!==typeof d.url&&c.push("url="+escape(d.url));a.href=e+"?"+c.join("&")}},getResolution:function(){var a=screen.width,b=screen.height,e,d,c="N",g=screen.colorDepth;"undefined"!=typeof window.innerWidth?(e=window.innerWidth,d=window.innerHeight,c="N1"):"undefined"!=typeof document.documentElement&&"undefined"!=
typeof document.documentElement.clientWidth&&0!=document.documentElement.clientWidth?(e=document.documentElement.clientWidth,d=document.documentElement.clientHeight,c="M1"):document.getElementsByTagName("body")?(e=document.getElementsByTagName("body")[0].clientWidth,d=document.getElementsByTagName("body")[0].clientHeight,c="M2"):(e=a,d=b,c="N2");return"resol="+escape("|"+e+"|"+d+"|"+c+"|"+a+"|"+b+"|"+g+"|")},xhr:!1,XMLHttpRequest:function(){var a=!1!=_gstat.xhr;if(!_gstat.xhr&&(window.XMLHttpRequest||
window.ActiveXObject))if(window.ActiveXObject)try{_gstat.xhr=new ActiveXObject("Msxml2.XMLHTTP"),a=!0}catch(b){_gstat.xhr=new ActiveXObject("Microsoft.XMLHTTP"),a=!0}else _gstat.xhr=new XMLHttpRequest,a=!0;return a}};
